[package]
name = "most-recent-file"
version = "0.1.0"
authors = ["developer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "0.4.18"
itertools = "0.10.1"
rayon = "1.5.1"
structopt = "0.3.22"
